site_name: fastapi-mvc
site_description: Create and develop production grade FastaAPI projects.
site_url: https://fastapi-mvc.netlify.app/
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
repo_name: rszamszur/fastapi-mvc
repo_url: https://github.com/rszamszur/fastapi-mvc/
plugins:
  - search
nav:
  - Overview: index.md
  - Install: install.md
  - Usage:
      - Creating a New Project: usage/create.md
      - Development: usage/development.md
      - Configuration: usage/configuration.md
  - Deployment:
      - Kubernetes: deployment/kubernetes.md
      - Docker: deployment/docker.md
      - Manually on a Server: deployment/manually.md
  - Contributing to fastapi-mvc: contributing.md
  - Changelog: changelog.md
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- toc:
    permalink: true
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
- admonition
- codehilite
- extra
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences