name: Build Docs

on:
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Load Poetry cache
        uses: actions/cache@v2
        with:
          path: ~/.poetry
          key: poetry-3.9-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/poetry.lock') }}
      - name: Config path and poetry
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH
          $HOME/.poetry/bin/poetry config cache-dir $HOME/.poetry/store
      - name: Build documentation
        run: |
          make docs
          echo "docs_build_name=docs-$(cat TAG)-$GITHUB_SHA" >> $GITHUB_ENV
      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.docs_build_name }}
          path: site
          retention-days: 60
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: site
          production-deploy: false
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}